In [ ]:
# import pandas as pd
# data = pd.read_parquet('/kaggle/input/datasets/leonardcaceres/alpha-maga/train_data.parquet').head()

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/leonardcaceres/alpha-maga/train_data.parquet'

In [ ]:
# data.info(True)
# del data

In [ ]:
import pandas as pd
data = pd.read_csv('/content/submission (2).csv')
print(data.shape)
data['id'] = data['id'].astype(int)
data['flag'] = data['flag'].astype(float)

(900000, 2)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data.to_csv('/content/drive/MyDrive/T-Bank/aboba.csv', index = False)

# вывы

In [ ]:
# import pandas as pd
# import pyarrow.parquet as pq
# import lightgbm as lgb
# import gc

# # 1. Загружаем таргет (маленький CSV) в словарь id -> flag
# target_df = pd.read_csv('/kaggle/input/datasets/leonardcaceres/id-data/dataset_alpha_id.csv')
# id_to_flag = dict(zip(target_df['id'], target_df['flag']))
# del target_df
# gc.collect()
# print(f"Загружено {len(id_to_flag)} записей таргета")

# # 2. Параметры LightGBM, настроенные на экономию памяти
# params = {
#     'objective': 'binary',
#     'metric': 'auc',
#     'learning_rate': 0.05,
#     'num_leaves': 127,          # уменьшено со стандартных 255
#     'max_bin': 128,             # меньше бинов = меньше памяти
#     'min_data_in_leaf': 100,    # более толстые листья
#     'feature_fraction': 0.8,
#     'bagging_fraction': 0.8,
#     'bagging_freq': 5,
#     'verbose': -1,
#     'random_state': 42,
#     'n_jobs': -1,
#     'warm_start': True          # ключевой параметр: продолжать обучение на новых чанках
# }

# # 3. Создаём модель (пока без обучения)
# model = lgb.LGBMClassifier(**params)

In [ ]:
# # 4. Читаем parquet блоками (чанками) и обучаем модель инкрементально
# parquet_path = '/kaggle/input/datasets/leonardcaceres/alpha-maga/train_data.parquet'
# parquet_file = pq.ParquetFile(parquet_path)
# batch_size = 500000   # количество строк в одном чанке (можно менять в зависимости от памяти)
# batch_size = 5000000   # количество строк в одном чанке (можно менять в зависимости от памяти)

In [ ]:
# print("Начинаем инкрементальное обучение...")
# for i, batch in enumerate(parquet_file.iter_batches(batch_size=batch_size)):
#     # Конвертируем батч в pandas DataFrame
#     df_batch = batch.to_pandas()

#     # Добавляем колонку таргета по id
#     df_batch['flag'] = df_batch['id'].map(id_to_flag)

#     # Удаляем строки, для которых не нашлось таргета (если такие есть)
#     df_batch.dropna(subset=['flag'], inplace=True)

#     if len(df_batch) == 0:
#         continue

#     # Отделяем признаки (все колонки, кроме id и flag)
#     X_batch = df_batch.drop(columns=['id', 'flag'])
#     y_batch = df_batch['flag']

#     # Обучаем модель на текущем чанке
#     # При первом вызове fit модель инициализируется,
#     # при последующих – продолжает обучение (благодаря warm_start=True)
#     model.fit(X_batch, y_batch)

#     print(f"Блок {i+1}: обработано {len(df_batch)} строк, деревьев в модели: {model.n_estimators_}")

#     # Очищаем память от ненужных объектов
#     del df_batch, X_batch, y_batch
#     gc.collect()

# print("Обучение завершено!")

In [ ]:
# import joblib
# joblib.dump(model, 'lightgbm_model.pkl')
# print("Модель сохранена в 'lightgbm_model.pkl'")

In [ ]:
# # 5. Модель готова к использованию
# # Например, предсказание на тестовых данных:
# test_df = pd.read_parquet('/kaggle/input/datasets/leonardcaceres/alpha-maga/test_data.parquet')
# test_df['predictions'] = model.predict_proba(test_df.drop(columns=['id']))[:, 1]

In [ ]:
test_df

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag,predictions
0,2250005,1,3,3,15,9,15,14,1,2,...,3,3,4,1,3,4,1,0,0,0.067638
1,2250005,2,9,2,15,12,1,11,19,6,...,3,3,4,1,2,4,1,0,0,0.058992
2,2250005,3,19,6,16,9,12,11,3,1,...,3,3,4,1,2,4,1,0,0,0.131119
3,2250005,4,19,16,15,9,12,11,12,1,...,3,3,4,1,2,4,1,0,0,0.058601
4,2250013,1,16,7,16,9,4,9,6,2,...,3,3,4,1,3,3,1,0,0,0.024005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7845696,1249988,3,19,6,13,0,1,11,12,3,...,3,3,4,1,5,4,1,0,0,0.038204
7845697,1249990,1,15,7,1,15,13,13,14,2,...,3,3,4,1,3,3,1,0,0,0.034768
7845698,1249990,2,14,0,0,8,7,11,15,2,...,3,3,4,1,2,3,1,0,1,0.025941
7845699,1249990,3,17,3,6,15,0,14,2,2,...,3,3,4,1,3,0,1,0,0,0.010288
7845700,1249990,4,1,6,6,1,0,4,2,5,...,3,3,4,1,2,0,1,0,0,0.016412

In [ ]:
pd.read_parquet('/kaggle/input/datasets/leonardcaceres/alpha-maga/test_data.parquet')

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag
0,2250005,1,3,3,15,9,15,14,1,2,...,3,3,3,4,1,3,4,1,0,0
1,2250005,2,9,2,15,12,1,11,19,6,...,3,3,3,4,1,2,4,1,0,0
2,2250005,3,19,6,16,9,12,11,3,1,...,3,3,3,4,1,2,4,1,0,0
3,2250005,4,19,16,15,9,12,11,12,1,...,3,3,3,4,1,2,4,1,0,0
4,2250013,1,16,7,16,9,4,9,6,2,...,3,3,3,4,1,3,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7845696,1249988,3,19,6,13,0,1,11,12,3,...,3,3,3,4,1,5,4,1,0,0
7845697,1249990,1,15,7,1,15,13,13,14,2,...,3,3,3,4,1,3,3,1,0,0
7845698,1249990,2,14,0,0,8,7,11,15,2,...,3,3,3,4,1,2,3,1,0,1
7845699,1249990,3,17,3,6,15,0,14,2,2,...,3,3,3,4,1,3,0,1,0,0
7845700,1249990,4,1,6,6,1,0,4,2,5,...,3,3,3,4,1,2,0,1,0,0

In [ ]:
subm = pd.read_csv('/kaggle/input/datasets/leonardcaceres/alpha-maga/sample_submission (2).csv')
subm

             id      flag
0             4  0.851663
1             8  0.109529
2            10  0.638577
3            15  0.107343
4            16  0.345646
...         ...       ...
899995  2999962  0.950884
899996  2999965  0.594869
899997  2999980  0.396822
899998  2999983  0.122627
899999  2999988  0.102047

[900000 rows x 2 columns]

In [ ]:
# 1. Группируем test_df по id и берём максимум predictions
max_predictions = test_df.groupby('id')['predictions'].max().reset_index()

In [ ]:
# 2. Присоединяем к subm (предполагается, что в subm есть колонка id)
subm = subm.merge(max_predictions, on='id', how='left', suffixes=('', '_max'))

In [ ]:
subm

             id      flag  predictions
0             4  0.851663     0.048006
1             8  0.109529     0.199544
2            10  0.638577     0.059123
3            15  0.107343     0.059377
4            16  0.345646     0.067273
...         ...       ...          ...
899995  2999962  0.950884     0.044657
899996  2999965  0.594869     0.110214
899997  2999980  0.396822     0.092713
899998  2999983  0.122627     0.035310
899999  2999988  0.102047     0.043464

[900000 rows x 3 columns]

In [ ]:
# 3. Если нужно переименовать колонку с максимальными предсказаниями в 'prediction'
subm['flag'] = subm['predictions']

# 4. Удаляем временную колонку (если не нужна)
subm.drop('predictions', axis=1, inplace=True)

In [ ]:
subm

             id      flag
0             4  0.048006
1             8  0.199544
2            10  0.059123
3            15  0.059377
4            16  0.067273
...         ...       ...
899995  2999962  0.044657
899996  2999965  0.110214
899997  2999980  0.092713
899998  2999983  0.035310
899999  2999988  0.043464

[900000 rows x 2 columns]

In [ ]:
subm.to_csv('sample_subm.csv',index = False)

# агрегация по клиенту

In [ ]:
import pandas as pd
import pyarrow.parquet as pq
import numpy as np
from collections import defaultdict, Counter
import gc

In [ ]:
# # 1. Загрузка таргета
# target_df = pd.read_csv('/kaggle/input/datasets/leonardcaceres/alpha-maga/train_target.csv')
# id_to_flag = dict(zip(target_df['id'], target_df['flag']))
# del target_df
# gc.collect()
# print(f"Загружено {len(id_to_flag)} записей таргета")

# # 2. Инкрементальная агрегация
# parquet_path_train = '/kaggle/input/datasets/leonardcaceres/alpha-maga/train_data.parquet'
# batch_size = 2_000_000   # уменьшил для баланса памяти/скорости (можно подбирать)

# aggs = defaultdict(lambda: {
#     'cnt': 0,
#     'sum_credit_limit': 0, 'sum_outstanding': 0, 'sum_overdue': 0,
#     'sum_max_overdue': 0, 'sum_util': 0, 'sum_over2limit': 0,
#     'sum_maxover2limit': 0, 'sum_loans5': 0, 'sum_loans530': 0,
#     'sum_loans3060': 0, 'sum_loans6090': 0, 'sum_loans90': 0,
#     'sum_pterm': 0, 'sum_fterm': 0, 'sum_next_pay_summ': 0,
#     'max_rn': -1, 'min_rn': 10**9,
#     'last_util': None, 'last_over2limit': None, 'last_loans90': None,
#     'last_credit_limit': None, 'last_outstanding': None,
#     'first_util': None, 'first_credit_limit': None,
#     'any_pclose_flag': False, 'any_fclose_flag': False,
#     'sum_paym': [0]*25,
#     'cnt_paym': 0,
#     'holder_counter': Counter(),
#     'status_counter': Counter(),
#     'type_counter': Counter(),
#     'cur_counter': Counter(),
# })

# print("Начинаем агрегацию тренировочных данных...")
# parquet_file = pq.ParquetFile(parquet_path_train)
# chunk_num = 0

# for batch in parquet_file.iter_batches(batch_size=batch_size):
#     df = batch.to_pandas()

#     # ---- 1. Агрегация простых сумм и экстремумов ----
#     simple_agg = df.groupby('id').agg(
#         cnt=('rn', 'count'),
#         sum_credit_limit=('pre_loans_credit_limit', 'sum'),
#         sum_outstanding=('pre_loans_outstanding', 'sum'),
#         sum_overdue=('pre_loans_total_overdue', 'sum'),
#         sum_max_overdue=('pre_loans_max_overdue_sum', 'sum'),
#         sum_util=('pre_util', 'sum'),
#         sum_over2limit=('pre_over2limit', 'sum'),
#         sum_maxover2limit=('pre_maxover2limit', 'sum'),
#         sum_loans5=('pre_loans5', 'sum'),
#         sum_loans530=('pre_loans530', 'sum'),
#         sum_loans3060=('pre_loans3060', 'sum'),
#         sum_loans6090=('pre_loans6090', 'sum'),
#         sum_loans90=('pre_loans90', 'sum'),
#         sum_pterm=('pre_pterm', 'sum'),
#         sum_fterm=('pre_fterm', 'sum'),
#         sum_next_pay_summ=('pre_loans_next_pay_summ', 'sum'),
#         max_rn=('rn', 'max'),
#         min_rn=('rn', 'min'),
#         any_pclose_flag=('pclose_flag', lambda x: (x == 1).any()),
#         any_fclose_flag=('fclose_flag', lambda x: (x == 1).any()),
#     ).reset_index()

#     # ---- 2. Значения для последнего (max rn) и первого (min rn) кредита ----
#     idx_max = df.groupby('id')['rn'].idxmax().values
#     idx_min = df.groupby('id')['rn'].idxmin().values
#     last_rows = df.loc[idx_max, ['id', 'pre_util', 'pre_over2limit', 'pre_loans90',
#                                  'pre_loans_credit_limit', 'pre_loans_outstanding']]
#     first_rows = df.loc[idx_min, ['id', 'pre_util', 'pre_loans_credit_limit']]

#     last_rows = last_rows.rename(columns={
#         'pre_util': 'last_util', 'pre_over2limit': 'last_over2limit',
#         'pre_loans90': 'last_loans90', 'pre_loans_credit_limit': 'last_credit_limit',
#         'pre_loans_outstanding': 'last_outstanding'
#     })
#     first_rows = first_rows.rename(columns={
#         'pre_util': 'first_util', 'pre_loans_credit_limit': 'first_credit_limit'
#     })

#     simple_agg = simple_agg.merge(last_rows, on='id', how='left')
#     simple_agg = simple_agg.merge(first_rows, on='id', how='left')

#     # ---- 3. Суммы по enc_paym_* ----
#     paym_cols = [f'enc_paym_{i}' for i in range(25)]
#     paym_sum = df.groupby('id')[paym_cols].sum().reset_index()

#     # ---- 4. Категориальные признаки → сбор в списки (временно) ----
#     cat_cols = ['enc_loans_account_holder_type', 'enc_loans_credit_status',
#                 'enc_loans_credit_type', 'enc_loans_account_cur']
#     cat_agg = {}
#     for col in cat_cols:
#         grouped = df.groupby('id')[col].agg(list).reset_index()
#         grouped.columns = ['id', f'{col}_list']
#         cat_agg[col] = grouped

#     # ---- 5. Обновление общего словаря aggs ----
#     # Обновление числовых агрегатов и флагов
#     for _, row in simple_agg.iterrows():
#         id_ = row['id']
#         rec = aggs[id_]
#         rec['cnt'] += row['cnt']
#         rec['sum_credit_limit'] += row['sum_credit_limit']
#         rec['sum_outstanding'] += row['sum_outstanding']
#         rec['sum_overdue'] += row['sum_overdue']
#         rec['sum_max_overdue'] += row['sum_max_overdue']
#         rec['sum_util'] += row['sum_util']
#         rec['sum_over2limit'] += row['sum_over2limit']
#         rec['sum_maxover2limit'] += row['sum_maxover2limit']
#         rec['sum_loans5'] += row['sum_loans5']
#         rec['sum_loans530'] += row['sum_loans530']
#         rec['sum_loans3060'] += row['sum_loans3060']
#         rec['sum_loans6090'] += row['sum_loans6090']
#         rec['sum_loans90'] += row['sum_loans90']
#         rec['sum_pterm'] += row['sum_pterm']
#         rec['sum_fterm'] += row['sum_fterm']
#         rec['sum_next_pay_summ'] += row['sum_next_pay_summ']
#         rec['any_pclose_flag'] = rec['any_pclose_flag'] or row['any_pclose_flag']
#         rec['any_fclose_flag'] = rec['any_fclose_flag'] or row['any_fclose_flag']

#         # Обновление last/first с проверкой глобального max/min rn
#         if row['max_rn'] > rec['max_rn']:
#             rec['max_rn'] = row['max_rn']
#             rec['last_util'] = row['last_util']
#             rec['last_over2limit'] = row['last_over2limit']
#             rec['last_loans90'] = row['last_loans90']
#             rec['last_credit_limit'] = row['last_credit_limit']
#             rec['last_outstanding'] = row['last_outstanding']
#         if row['min_rn'] < rec['min_rn']:
#             rec['min_rn'] = row['min_rn']
#             rec['first_util'] = row['first_util']
#             rec['first_credit_limit'] = row['first_credit_limit']

#     # Обновление sum_paym
#     for _, row in paym_sum.iterrows():
#         id_ = row['id']
#         rec = aggs[id_]
#         for j in range(25):
#             rec['sum_paym'][j] += row[paym_cols[j]]

#     # Обновление категориальных счётчиков
#     for col in cat_cols:
#         col_list_df = cat_agg[col]
#         for _, row in col_list_df.iterrows():
#             id_ = row['id']
#             counter = Counter(row[f'{col}_list'])
#             if col == 'enc_loans_account_holder_type':
#                 aggs[id_]['holder_counter'].update(counter)
#             elif col == 'enc_loans_credit_status':
#                 aggs[id_]['status_counter'].update(counter)
#             elif col == 'enc_loans_credit_type':
#                 aggs[id_]['type_counter'].update(counter)
#             else:  # enc_loans_account_cur
#                 aggs[id_]['cur_counter'].update(counter)

#     # После обновления cnt_paym можно установить равным cnt (сделаем позже при формировании признаков)
#     chunk_num += 1
#     print(f"Обработано {chunk_num} чанков, уникальных id: {len(aggs)}")
#     del df, simple_agg, paym_sum, cat_agg, last_rows, first_rows
#     gc.collect()

# print(f"Агрегация закончена. Уникальных клиентов: {len(aggs)}")

In [ ]:

# # ---- 6. Формирование итогового DataFrame с признаками ----
# rows = []
# for id_, d in aggs.items():
#     cnt = d['cnt']
#     if cnt == 0:
#         continue
#     row = {'id': id_}
#     row['cnt_loans'] = cnt
#     row['mean_credit_limit'] = d['sum_credit_limit'] / cnt
#     row['mean_outstanding'] = d['sum_outstanding'] / cnt
#     row['mean_util'] = d['sum_util'] / cnt
#     row['mean_overdue'] = d['sum_overdue'] / cnt
#     row['mean_max_overdue'] = d['sum_max_overdue'] / cnt
#     row['mean_next_pay_summ'] = d['sum_next_pay_summ'] / cnt
#     row['mean_pterm'] = d['sum_pterm'] / cnt
#     row['mean_fterm'] = d['sum_fterm'] / cnt

#     row['total_loans5'] = d['sum_loans5']
#     row['total_loans530'] = d['sum_loans530']
#     row['total_loans3060'] = d['sum_loans3060']
#     row['total_loans6090'] = d['sum_loans6090']
#     row['total_loans90'] = d['sum_loans90']
#     row['weighted_overdue'] = (1*d['sum_loans5'] + 2*d['sum_loans530'] +
#                                3*d['sum_loans3060'] + 4*d['sum_loans6090'] +
#                                5*d['sum_loans90'])
#     if d['sum_loans90'] > 0:
#         row['max_overdue_level'] = 5
#     elif d['sum_loans6090'] > 0:
#         row['max_overdue_level'] = 4
#     elif d['sum_loans3060'] > 0:
#         row['max_overdue_level'] = 3
#     elif d['sum_loans530'] > 0:
#         row['max_overdue_level'] = 2
#     elif d['sum_loans5'] > 0:
#         row['max_overdue_level'] = 1
#     else:
#         row['max_overdue_level'] = 0

#     row['outstanding_to_limit'] = d['sum_outstanding'] / (d['sum_credit_limit'] + 1e-9)
#     row['overdue_to_limit'] = d['sum_overdue'] / (d['sum_credit_limit'] + 1e-9)
#     row['next_paym_to_outstanding'] = d['sum_next_pay_summ'] / (d['sum_outstanding'] + 1e-9)

#     row['last_util'] = d['last_util'] if d['last_util'] is not None else 0
#     row['last_over2limit'] = d['last_over2limit'] if d['last_over2limit'] is not None else 0
#     row['last_loans90'] = d['last_loans90'] if d['last_loans90'] is not None else 0
#     row['last_credit_limit'] = d['last_credit_limit'] if d['last_credit_limit'] is not None else 0
#     row['last_outstanding'] = d['last_outstanding'] if d['last_outstanding'] is not None else 0

#     row['first_util'] = d['first_util'] if d['first_util'] is not None else 0
#     row['first_credit_limit'] = d['first_credit_limit'] if d['first_credit_limit'] is not None else 0

#     row['trend_util'] = row['last_util'] - row['first_util']
#     row['trend_credit_limit'] = row['last_credit_limit'] - row['first_credit_limit']

#     row['any_pclose_flag'] = int(d['any_pclose_flag'])
#     row['any_fclose_flag'] = int(d['any_fclose_flag'])

#     # Обработка paym
#     d['cnt_paym'] = cnt  # приравниваем cnt_paym к общему количеству строк
#     paym_mean = [s / d['cnt_paym'] for s in d['sum_paym']]
#     row['avg_paym'] = np.mean(paym_mean)
#     row['max_paym'] = np.max(paym_mean)
#     row['std_paym'] = np.std(paym_mean)
#     if len(paym_mean) >= 24:
#         row['trend_paym_first12'] = np.mean(paym_mean[:12])
#         row['trend_paym_last12'] = np.mean(paym_mean[-12:])
#         row['trend_paym_diff'] = row['trend_paym_last12'] - row['trend_paym_first12']
#     else:
#         row['trend_paym_first12'] = np.nan
#         row['trend_paym_last12'] = np.nan
#         row['trend_paym_diff'] = np.nan

#     # Категориальные статистики
#     if d['holder_counter']:
#         row['mode_holder_type'] = d['holder_counter'].most_common(1)[0][0]
#         row['nunique_holder_type'] = len(d['holder_counter'])
#     else:
#         row['mode_holder_type'] = -1
#         row['nunique_holder_type'] = 0
#     if d['status_counter']:
#         row['mode_credit_status'] = d['status_counter'].most_common(1)[0][0]
#         row['nunique_credit_status'] = len(d['status_counter'])
#     else:
#         row['mode_credit_status'] = -1
#         row['nunique_credit_status'] = 0
#     if d['type_counter']:
#         row['mode_credit_type'] = d['type_counter'].most_common(1)[0][0]
#         row['nunique_credit_type'] = len(d['type_counter'])
#     else:
#         row['mode_credit_type'] = -1
#         row['nunique_credit_type'] = 0
#     if d['cur_counter']:
#         row['mode_account_cur'] = d['cur_counter'].most_common(1)[0][0]
#         row['nunique_account_cur'] = len(d['cur_counter'])
#     else:
#         row['mode_account_cur'] = -1
#         row['nunique_account_cur'] = 0

#     rows.append(row)

# df_train_features = pd.DataFrame(rows)
# print(f"Размерность тренировочных фичей: {df_train_features.shape}")

In [ ]:
# df_train_features.to_csv('df_train_agg.csv', index = False)

In [ ]:
# del rows, aggs
# gc.collect()

In [ ]:
# df_train_features.to_parquet('df_train_agg.parquet')

In [ ]:
# df_train_features.to_parquet('df_train_agg.parquet')

In [ ]:
data = pd.read_parquet('/content/df_train_agg.parquet')
target = pd.read_csv('/content/train_target.csv')
dataset = data.merge(target[['id', 'flag']])
print(dataset.shape, np.sum(dataset['flag']))
dataset.head()

(2100000, 46) 74509

,id,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,...,trend_paym_diff,mode_holder_type,nunique_holder_type,mode_credit_status,nunique_credit_status,mode_credit_type,nunique_credit_type,mode_account_cur,nunique_account_cur,flag
0,2250000,8,9.375,3.125000,15.375000,0.0,2.0,2.500000,10.375000,8.250000,...,1.510417,1,1,3,2,4,3,1,1,0
1,2250001,2,9.500,2.500000,11.000000,0.0,2.0,1.500000,10.000000,8.000000,...,0.333333,1,1,3,2,5,2,1,1,0
2,2250002,9,10.000,3.666667,11.333333,0.0,2.0,2.444444,10.333333,8.888889,...,0.851852,1,2,2,2,3,4,1,1,0
3,2250003,4,5.750,3.000000,11.500000,0.0,2.0,2.000000,3.500000,6.250000,...,0.958333,1,1,2,2,3,2,1,1,0
4,2250004,1,16.000,3.000000,16.000000,0.0,3.0,1.000000,2.000000,14.000000,...,-0.250000,1,1,3,1,4,1,1,1,0

In [ ]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import pandas as pd

In [ ]:
# ----------------------------------------------
# 1. Подготовка данных (если ещё не разделены)
# ----------------------------------------------
X = dataset.drop(['id', 'flag'], axis=1)
y = dataset['flag']

# Разделяем на train/val для честной оценки (стратификация по y)
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# # ----------------------------------------------
# # 2. Обучение модели без отбора фичей
# # ----------------------------------------------
# params = {
#     'objective': 'binary',
#     'metric': 'auc',
#     # 'boosting_type': 'gbdt',
#     'num_leaves': 127,          # можно поднять до 255, если памяти достаточно
#     'learning_rate': 0.05,
#     # 'feature_fraction': 0.8,
#     # 'bagging_fraction': 0.8,
#     # 'bagging_freq': 5,
#     'min_data_in_leaf': 100,
#     'max_bin': 255,
#     'verbose': -1,
#     'random_state': 42,
#     'n_jobs': -1
# }

# model = lgb.LGBMClassifier(**params)

# # Обучение с early stopping на валидации
# model.fit(
#     X_train, y_train,
#     eval_set=[(X_val, y_val)],
#     eval_metric='auc',
#     callbacks=[
#         lgb.early_stopping(stopping_rounds=50, verbose=True),
#         lgb.log_evaluation(100)
#     ]
# )

# # ----------------------------------------------
# # 3. Оценка качества
# # ----------------------------------------------
# y_pred = model.predict_proba(X_val)[:, 1]
# auc = roc_auc_score(y_val, y_pred)
# print(f"Validation ROC-AUC: {auc:.6f}")

In [ ]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import pandas as pd
import numpy as np

In [ ]:
# ----------------------------------------------
# 0. Добавление новых финансовых признаков
# ----------------------------------------------
df = dataset.copy()

# Свободный кредитный лимит (средний лимит минус средний остаток)
df['free_limit_ratio'] = (df['mean_credit_limit'] - df['mean_outstanding']) / (df['mean_credit_limit'] + 1e-9)

# Доля просроченной задолженности к общему лимиту
df['overdue_to_credit_limit_ratio'] = df['mean_overdue'] / (df['mean_credit_limit'] + 1e-9)

# Коэффициент платежной нагрузки: средний платёж к среднему остатку
df['payment_to_outstanding_ratio'] = df['mean_next_pay_summ'] / (df['mean_outstanding'] + 1e-9)

# Средняя сумма просрочки на один продукт
df['avg_overdue_per_loan'] = df['mean_overdue'] / (df['cnt_loans'] + 1e-9)

# Средний уровень максимальной просрочки на продукт
df['avg_max_overdue_per_loan'] = df['mean_max_overdue'] / (df['cnt_loans'] + 1e-9)

# Коэффициент использования лимита (отношение среднего к последнему util)
df['util_mean_to_max'] = df['mean_util'] / (df['last_util'] + 1e-9)

# Отношение последнего util к первому (динамика использования)
df['util_trend_ratio'] = (df['last_util'] + 1e-9) / (df['first_util'] + 1e-9)

# Флаг наличия просрочек
df['has_overdue'] = (df['max_overdue_level'] > 0).astype(int)

# Доля продуктов с просрочками >30 дней
df['high_overdue_ratio'] = ((df['total_loans3060'] + df['total_loans6090'] + df['total_loans90']) / (df['cnt_loans'] + 1e-9)).clip(0, 1)

# Показатель стабильности платежей (обратная вариация)
df['paym_stability'] = 1.0 / (df['std_paym'] + 1e-9)

# Отношение планового срока к фактическому
df['mean_term_ratio'] = df['mean_pterm'] / (df['mean_fterm'] + 1e-9)

# ----------------------------------------------
# Дополнительные финансовые признаки
# ----------------------------------------------
# Отношение среднего платежа к кредитному лимиту (платёжная нагрузка на лимит)
df['payment_to_limit_ratio'] = df['mean_next_pay_summ'] / (df['mean_credit_limit'] + 1e-9)

# Отношение максимальной просрочки к среднему остатку (тяжесть дефолта)
df['max_overdue_to_outstanding_ratio'] = df['mean_max_overdue'] / (df['mean_outstanding'] + 1e-9)

# Скорость накопления просрочек (средняя просрочка на один кредит с весами)
df['overdue_intensity'] = (df['weighted_overdue'] + 1e-9) / (df['cnt_loans'] + 1e-9)

# Отношение фактического срока к плановому (чем больше, тем дольше выплачивает)
df['actual_to_plan_term_ratio'] = df['mean_fterm'] / (df['mean_pterm'] + 1e-9)

# Доля продуктов, где util близок к 100% (критическая загрузка)
df['critical_util_ratio'] = ((df['mean_util'] > 0.95) & (df['mean_util'] <= 1.05)).astype(int)

# Тренд util относительно среднего (последний util / средний util)
df['last_vs_mean_util'] = df['last_util'] / (df['mean_util'] + 1e-9)

# Индекс платёжной дисциплины (обратная пропорция просрочек)
df['payment_discipline'] = 1.0 / (df['weighted_overdue'] + df['total_loans90'] + 1e-9)

# Комбинированный риск-фактор (высокие просрочки + низкий свободный лимит)
df['risk_factor'] = (
    df['high_overdue_ratio'] * (1 - df['free_limit_ratio'].clip(0, 1))
)

# Изменение util от первого к последнему продукту (нормированное)
df['util_change_rate'] = (df['last_util'] - df['first_util']) / (df['first_util'] + 1e-9)

# Признак: есть ли кредиты с плановым сроком меньше фактического (признак реструктуризации)
df['has_renegotiated'] = ((df['mean_fterm'] - df['mean_pterm']) > 0).astype(int)


# Интегральный индекс финансового здоровья
df['financial_health_index'] = (
    df['free_limit_ratio'] * 0.3
    - df['overdue_to_credit_limit_ratio'] * 0.4
    - df['high_overdue_ratio'] * 0.3
)

# Заполняем возможные NaN
df = df.fillna(0)

# ----------------------------------------------
# 1. Подготовка данных
# ----------------------------------------------
X = df.drop(['id', 'flag'], axis=1)
y = df['flag']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# ----------------------------------------------
# 2. Обучение модели LightGBM
# ----------------------------------------------
params = {
    'objective': 'binary',
    'metric': 'auc',
    'num_leaves': 127,
    'learning_rate': 0.05,
    'min_data_in_leaf': 100,
    'max_bin': 255,
    'verbose': -1,
    'random_state': 42,
    'n_jobs': -1
}

model = lgb.LGBMClassifier(**params)

model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    eval_metric='auc',
    callbacks=[
        lgb.early_stopping(stopping_rounds=50, verbose=True),
        lgb.log_evaluation(100)
    ]
)

# ----------------------------------------------
# 3. Оценка качества
# ----------------------------------------------
y_pred = model.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print(f"Validation ROC-AUC: {auc:.6f}")

In [ ]:
import optuna
from optuna.samplers import TPESampler
import lightgbm as lgb
from sklearn.metrics import roc_auc_score

# ----------------------------------------------
# 4. Оптимизация гиперпараметров с помощью Optuna
# ----------------------------------------------

def objective(trial):
    # Предлагаемые гиперпараметры
    params = {
        'objective': 'binary',
        'metric': 'auc',
        'boosting_type': 'gbdt',
        'verbosity': -1,
        'random_state': 42,
        'n_jobs': -1,

        # Основные параметры
        'n_estimators': trial.suggest_int('n_estimators', 100, 2000, step=50),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 16, 512),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'min_child_samples': trial.suggest_int('min_child_samples', 10, 200),
        'max_bin': trial.suggest_int('max_bin', 64, 512),

        # Регуляризация
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),

        # Стохастичность
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'subsample_freq': trial.suggest_int('subsample_freq', 1, 10),

        # Дополнительно
        'min_gain_to_split': trial.suggest_float('min_gain_to_split', 0.0, 1.0),
        'max_delta_step': trial.suggest_float('max_delta_step', 0.0, 5.0),
    }

    # Создаём модель и обучаем с ранней остановкой
    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='auc',
        callbacks=[
            lgb.early_stopping(stopping_rounds=30, verbose=False),
            lgb.log_evaluation(0)   # отключаем вывод внутри trial
        ]
    )

    # Предсказываем на валидации
    y_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_pred)
    return auc

# Создаём исследование
study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
study.optimize(objective, n_trials=10, show_progress_bar=True)

# Лучшие параметры
print("Best trial:")
best_trial = study.best_trial
print(f"  AUC: {best_trial.value:.6f}")
print("  Params: ")
for key, value in best_trial.params.items():
    print(f"    {key}: {value}")

# ----------------------------------------------
# 5. Обучение финальной модели с лучшими параметрами
# ----------------------------------------------
best_params = best_trial.params
# Добавляем фиксированные параметры
best_params.update({
    'objective': 'binary',
    'metric': 'auc',
    'verbose': -1,
    'random_state': 67,
    'n_jobs': -1
})

[I 2026-06-06 17:06:26,561] A new study created in memory with name: no-name-edc03728-4754-423b-8036-ebbb4ac56262

  0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-06-06 17:06:53,381] Trial 0 finished with value: 0.6966768111284648 and parameters: {'n_estimators': 800, 'learning_rate': 0.2536999076681772, 'num_leaves': 379, 'max_depth': 8, 'min_child_samples': 39, 'max_bin': 134, 'reg_alpha': 3.3323645788192616e-08, 'reg_lambda': 0.6245760287469893, 'subsample': 0.8005575058716043, 'colsample_bytree': 0.8540362888980227, 'subsample_freq': 1, 'min_gain_to_split': 0.9699098521619943, 'max_delta_step': 4.162213204002109}. Best is trial 0 with value: 0.6966768111284648.
[I 2026-06-06 17:09:00,785] Trial 1 finished with value: 0.702971452303683 and parameters: {'n_estimators': 500, 'learning_rate': 0.01855998084649059, 'num_leaves': 107, 'max_depth': 6, 'min_child_samples': 110, 'max_bin': 257, 'reg_alpha': 4.17890272377219e-06, 'reg_lambda': 0.0032112643094417484, 'subsample': 0.569746930326021, 'colsample_bytree': 0.6460723242676091, 'subsample_freq': 4, 'min_gain_to_split': 0.45606998421703593, 'max_delta_step': 3.925879806965068}. Best is trial 1 with value: 0.702971452303683.
[I 2026-06-06 17:10:44,681] Trial 2 finished with value: 0.7003434108246643 and parameters: {'n_estimators': 450, 'learning_rate': 0.05748924681991978, 'num_leaves': 310, 'max_depth': 3, 'min_child_samples': 126, 'max_bin': 140, 'reg_alpha': 3.850031979199519e-08, 'reg_lambda': 3.4671276804481113, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'subsample_freq': 4, 'min_gain_to_split': 0.09767211400638387, 'max_delta_step': 3.4211651325607844}. Best is trial 1 with value: 0.702971452303683.
[I 2026-06-06 17:13:55,813] Trial 3 finished with value: 0.6951019215970857 and parameters: {'n_estimators': 950, 'learning_rate': 0.015144860262751412, 'num_leaves': 262, 'max_depth': 3, 'min_child_samples': 183, 'max_bin': 180, 'reg_alpha': 0.009176996354542699, 'reg_lambda': 6.388511557344611e-06, 'subsample': 0.7600340105889054, 'colsample_bytree': 0.7733551396716398, 'subsample_freq': 2, 'min_gain_to_split': 0.9695846277645586, 'max_delta_step': 3.8756641168055728}. Best is trial 1 with value: 0.702971452303683.
[I 2026-06-06 17:14:25,192] Trial 4 finished with value: 0.6969689188921075 and parameters: {'n_estimators': 1900, 'learning_rate': 0.20978213384576816, 'num_leaves': 313, 'max_depth': 12, 'min_child_samples': 26, 'max_bin': 151, 'reg_alpha': 2.5529693461039728e-08, 'reg_lambda': 8.471746987003668e-06, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'subsample_freq': 9, 'min_gain_to_split': 0.3567533266935893, 'max_delta_step': 1.4046725484369038}. Best is trial 1 with value: 0.702971452303683.
[I 2026-06-06 17:18:08,092] Trial 5 finished with value: 0.6956354823901438 and parameters: {'n_estimators': 1150, 'learning_rate': 0.016149614799999188, 'num_leaves': 414, 'max_depth': 3, 'min_child_samples': 198, 'max_bin': 410, 'reg_alpha': 6.143857495033091e-07, 'reg_lambda': 1.1212412169964432e-08, 'subsample': 0.9077307142274171, 'colsample_bytree': 0.8534286719238086, 'subsample_freq': 8, 'min_gain_to_split': 0.7712703466859457, 'max_delta_step': 0.3702232586704518}. Best is trial 1 with value: 0.702971452303683.
[I 2026-06-06 17:23:36,559] Trial 6 finished with value: 0.7074148295965769 and parameters: {'n_estimators': 750, 'learning_rate': 0.014830392684568025, 'num_leaves': 444, 'max_depth': 9, 'min_child_samples': 73, 'max_bin': 92, 'reg_alpha': 6.292756043818863e-06, 'reg_lambda': 8.445977074223802e-06, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'subsample_freq': 9, 'min_gain_to_split': 0.4722149251619493, 'max_delta_step': 0.5979712296915085}. Best is trial 6 with value: 0.7074148295965769.
[I 2026-06-06 17:24:13,101] Trial 7 finished with value: 0.6978684773718533 and parameters: {'n_estimators': 1450, 'learning_rate': 0.13297554090738672, 'num_leaves': 294, 'max_depth': 10, 'min_child_samples': 104, 'max_bin': 298, 'reg_alpha': 7.04480806377519e-05, 'reg_lambda': 1.6934490731313353e-08, 'subsample': 0.5539457134966522, 'colsample_bytree': 0.5157145928433671, 'subsample_freq': 7, 'min_gain_to_split': 0.3143559810763267, 'max_delta_step': 2.542853455823514}. Best is trial 6 with value: 0.7074148295965769.
[I 2026-06-06 17:28:29,990] Trial 8 finished with value: 0.706811624610942 and parameters: {'n_estimators': 1850, 'learning_rate': 0.02334720250903525, 'num_leaves': 219, 'max_depth': 10, 'min_child_samples': 53, 'max_bin': 98, 'reg_alpha': 4.052873758065144e-06, 'reg_lambda': 2.824825241715838e-07, 'subsample': 0.9648488261712865, 'colsample_bytree': 0.9040601897822085, 'subsample_freq': 7, 'min_gain_to_split': 0.8714605901877177, 'max_delta_step': 4.018360384495573}. Best is trial 6 with value: 0.7074148295965769.
[I 2026-06-06 17:29:00,841] Trial 9 finished with value: 0.6946724399653644 and parameters: {'n_estimators': 450, 'learning_rate': 0.20816986844858934, 'num_leaves': 284, 'max_depth': 11, 'min_child_samples': 181, 'max_bin': 206, 'reg_alpha': 9.782893389157736e-08, 'reg_lambda': 1.1256839212661599e-06, 'subsample': 0.7135538943131281, 'colsample_bytree': 0.9090073829612466, 'subsample_freq': 9, 'min_gain_to_split': 0.006952130531190703, 'max_delta_step': 2.553736512887829}. Best is trial 6 with value: 0.7074148295965769.
Best trial:
  AUC: 0.707415
  Params:
    n_estimators: 750
    learning_rate: 0.014830392684568025
    num_leaves: 444
    max_depth: 9
    min_child_samples: 73
    max_bin: 92
    reg_alpha: 6.292756043818863e-06
    reg_lambda: 8.445977074223802e-06
    subsample: 0.864803089169032
    colsample_bytree: 0.8187787356776066
    subsample_freq: 9
    min_gain_to_split: 0.4722149251619493
    max_delta_step: 0.5979712296915085
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.686162
[200]	valid_0's auc: 0.695284
[300]	valid_0's auc: 0.700429
[400]	valid_0's auc: 0.703433
[500]	valid_0's auc: 0.705147

KeyboardInterrupt:

In [ ]:
best_params = {'n_estimators': 750,
 'learning_rate': 0.014830392684568025,
 'num_leaves': 444,
 'max_depth': 9,
 'min_child_samples': 73,
 'max_bin': 92,
 'reg_alpha': 6.292756043818863e-06,
 'reg_lambda': 8.445977074223802e-06,
 'subsample': 0.864803089169032,
 'colsample_bytree': 0.8187787356776066,
 'subsample_freq': 9,
 'min_gain_to_split': 0.4722149251619493,
 'max_delta_step': 0.5979712296915085,
 'objective': 'binary',
 'metric': 'auc',
 'verbose': -1,
 'random_state': 67,
 'n_jobs': -1}

best_params

{'n_estimators': 750,
 'learning_rate': 0.014830392684568025,
 'num_leaves': 444,
 'max_depth': 9,
 'min_child_samples': 73,
 'max_bin': 92,
 'reg_alpha': 6.292756043818863e-06,
 'reg_lambda': 8.445977074223802e-06,
 'subsample': 0.864803089169032,
 'colsample_bytree': 0.8187787356776066,
 'subsample_freq': 9,
 'min_gain_to_split': 0.4722149251619493,
 'max_delta_step': 0.5979712296915085,
 'objective': 'binary',
 'metric': 'auc',
 'verbose': -1,
 'random_state': 67,
 'n_jobs': -1}

{'n_estimators': 750,
 'learning_rate': 0.014830392684568025,
 'num_leaves': 444,
 'max_depth': 9,
 'min_child_samples': 73,
 'max_bin': 92,
 'reg_alpha': 6.292756043818863e-06,
 'reg_lambda': 8.445977074223802e-06,
 'subsample': 0.864803089169032,
 'colsample_bytree': 0.8187787356776066,
 'subsample_freq': 9,
 'min_gain_to_split': 0.4722149251619493,
 'max_delta_step': 0.5979712296915085,
 'objective': 'binary',
 'metric': 'auc',
 'verbose': -1,
 'random_state': 67,
 'n_jobs': -1}

In [ ]:
final_model = lgb.LGBMClassifier(**best_params)
final_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    eval_metric='auc',
    callbacks=[
        lgb.early_stopping(stopping_rounds=50, verbose=True),
        lgb.log_evaluation(100)
    ]
)

# Оценка финальной модели
y_pred_final = final_model.predict_proba(X_val)[:, 1]
auc_final = roc_auc_score(y_val, y_pred_final)
print(f"Final Validation ROC-AUC after tuning: {auc_final:.6f}")

Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.686162
[200]	valid_0's auc: 0.695284
[300]	valid_0's auc: 0.700429
[400]	valid_0's auc: 0.703433
[500]	valid_0's auc: 0.705147
[600]	valid_0's auc: 0.706295
[700]	valid_0's auc: 0.707028
Did not meet early stopping. Best iteration is:
[749]	valid_0's auc: 0.707224
Final Validation ROC-AUC after tuning: 0.707224

In [ ]:
# Оценка финальной модели
y_pred_final = final_model.predict_proba(X_val)[:, 1]
auc_final = roc_auc_score(y_val, y_pred_final)
print(f"Final Validation ROC-AUC after tuning: {auc_final:.6f}")

In [ ]:
import joblib

# Сохраняем модель в файл
joblib.dump(final_model, 'lightgbm_final_model_new.pkl')
print("Модель сохранена как 'lightgbm_final_model.pkl'")

Модель сохранена как 'lightgbm_final_model.pkl'

In [ ]:
# Сохраняем
joblib.dump(final_model, 'my_model.pkl')
print("Модель сохранена как 'my_model.pkl'")

Модель сохранена как 'my_model.pkl'

In [ ]:
import joblib

final_model = joblib.load('/kaggle/working/lightgbm_final_model.pkl')
print("Модель загружена")

# Тестовые данные

In [ ]:
# ============================================================
# Агрегация и feature engineering для тестового датасета
# ============================================================

# 1. Агрегация тестовых данных (аналогично тренировочным)
parquet_path_test = '/kaggle/input/datasets/leonardcaceres/alpha-maga/test_data.parquet'
batch_size = 2_000_000
print('asa')
aggs_test = defaultdict(lambda: {
    'cnt': 0,
    'sum_credit_limit': 0, 'sum_outstanding': 0, 'sum_overdue': 0,
    'sum_max_overdue': 0, 'sum_util': 0, 'sum_over2limit': 0,
    'sum_maxover2limit': 0, 'sum_loans5': 0, 'sum_loans530': 0,
    'sum_loans3060': 0, 'sum_loans6090': 0, 'sum_loans90': 0,
    'sum_pterm': 0, 'sum_fterm': 0, 'sum_next_pay_summ': 0,
    'max_rn': -1, 'min_rn': 10**9,
    'last_util': None, 'last_over2limit': None, 'last_loans90': None,
    'last_credit_limit': None, 'last_outstanding': None,
    'first_util': None, 'first_credit_limit': None,
    'any_pclose_flag': False, 'any_fclose_flag': False,
    'sum_paym': [0]*25,
    'cnt_paym': 0,
    'holder_counter': Counter(),
    'status_counter': Counter(),
    'type_counter': Counter(),
    'cur_counter': Counter(),
})

print("Начинаем агрегацию тестовых данных...")
parquet_file_test = pq.ParquetFile(parquet_path_test)
chunk_num = 0

for batch in parquet_file_test.iter_batches(batch_size=batch_size):
    df = batch.to_pandas()

    # ---- Агрегация простых сумм и экстремумов ----
    simple_agg = df.groupby('id').agg(
        cnt=('rn', 'count'),
        sum_credit_limit=('pre_loans_credit_limit', 'sum'),
        sum_outstanding=('pre_loans_outstanding', 'sum'),
        sum_overdue=('pre_loans_total_overdue', 'sum'),
        sum_max_overdue=('pre_loans_max_overdue_sum', 'sum'),
        sum_util=('pre_util', 'sum'),
        sum_over2limit=('pre_over2limit', 'sum'),
        sum_maxover2limit=('pre_maxover2limit', 'sum'),
        sum_loans5=('pre_loans5', 'sum'),
        sum_loans530=('pre_loans530', 'sum'),
        sum_loans3060=('pre_loans3060', 'sum'),
        sum_loans6090=('pre_loans6090', 'sum'),
        sum_loans90=('pre_loans90', 'sum'),
        sum_pterm=('pre_pterm', 'sum'),
        sum_fterm=('pre_fterm', 'sum'),
        sum_next_pay_summ=('pre_loans_next_pay_summ', 'sum'),
        max_rn=('rn', 'max'),
        min_rn=('rn', 'min'),
        any_pclose_flag=('pclose_flag', lambda x: (x == 1).any()),
        any_fclose_flag=('fclose_flag', lambda x: (x == 1).any()),
    ).reset_index()

    # ---- Значения для последнего и первого кредита ----
    idx_max = df.groupby('id')['rn'].idxmax().values
    idx_min = df.groupby('id')['rn'].idxmin().values
    last_rows = df.loc[idx_max, ['id', 'pre_util', 'pre_over2limit', 'pre_loans90',
                                 'pre_loans_credit_limit', 'pre_loans_outstanding']]
    first_rows = df.loc[idx_min, ['id', 'pre_util', 'pre_loans_credit_limit']]

    last_rows = last_rows.rename(columns={
        'pre_util': 'last_util', 'pre_over2limit': 'last_over2limit',
        'pre_loans90': 'last_loans90', 'pre_loans_credit_limit': 'last_credit_limit',
        'pre_loans_outstanding': 'last_outstanding'
    })
    first_rows = first_rows.rename(columns={
        'pre_util': 'first_util', 'pre_loans_credit_limit': 'first_credit_limit'
    })

    simple_agg = simple_agg.merge(last_rows, on='id', how='left')
    simple_agg = simple_agg.merge(first_rows, on='id', how='left')

    # ---- Суммы по enc_paym_* ----
    paym_cols = [f'enc_paym_{i}' for i in range(25)]
    paym_sum = df.groupby('id')[paym_cols].sum().reset_index()

    # ---- Категориальные признаки -> списки ----
    cat_cols = ['enc_loans_account_holder_type', 'enc_loans_credit_status',
                'enc_loans_credit_type', 'enc_loans_account_cur']
    cat_agg = {}
    for col in cat_cols:
        grouped = df.groupby('id')[col].agg(list).reset_index()
        grouped.columns = ['id', f'{col}_list']
        cat_agg[col] = grouped

    # ---- Обновление словаря aggs_test ----
    for _, row in simple_agg.iterrows():
        id_ = row['id']
        rec = aggs_test[id_]
        rec['cnt'] += row['cnt']
        rec['sum_credit_limit'] += row['sum_credit_limit']
        rec['sum_outstanding'] += row['sum_outstanding']
        rec['sum_overdue'] += row['sum_overdue']
        rec['sum_max_overdue'] += row['sum_max_overdue']
        rec['sum_util'] += row['sum_util']
        rec['sum_over2limit'] += row['sum_over2limit']
        rec['sum_maxover2limit'] += row['sum_maxover2limit']
        rec['sum_loans5'] += row['sum_loans5']
        rec['sum_loans530'] += row['sum_loans530']
        rec['sum_loans3060'] += row['sum_loans3060']
        rec['sum_loans6090'] += row['sum_loans6090']
        rec['sum_loans90'] += row['sum_loans90']
        rec['sum_pterm'] += row['sum_pterm']
        rec['sum_fterm'] += row['sum_fterm']
        rec['sum_next_pay_summ'] += row['sum_next_pay_summ']
        rec['any_pclose_flag'] = rec['any_pclose_flag'] or row['any_pclose_flag']
        rec['any_fclose_flag'] = rec['any_fclose_flag'] or row['any_fclose_flag']

        if row['max_rn'] > rec['max_rn']:
            rec['max_rn'] = row['max_rn']
            rec['last_util'] = row['last_util']
            rec['last_over2limit'] = row['last_over2limit']
            rec['last_loans90'] = row['last_loans90']
            rec['last_credit_limit'] = row['last_credit_limit']
            rec['last_outstanding'] = row['last_outstanding']
        if row['min_rn'] < rec['min_rn']:
            rec['min_rn'] = row['min_rn']
            rec['first_util'] = row['first_util']
            rec['first_credit_limit'] = row['first_credit_limit']

    for _, row in paym_sum.iterrows():
        id_ = row['id']
        rec = aggs_test[id_]
        for j in range(25):
            rec['sum_paym'][j] += row[paym_cols[j]]

    for col in cat_cols:
        col_list_df = cat_agg[col]
        for _, row in col_list_df.iterrows():
            id_ = row['id']
            counter = Counter(row[f'{col}_list'])
            if col == 'enc_loans_account_holder_type':
                aggs_test[id_]['holder_counter'].update(counter)
            elif col == 'enc_loans_credit_status':
                aggs_test[id_]['status_counter'].update(counter)
            elif col == 'enc_loans_credit_type':
                aggs_test[id_]['type_counter'].update(counter)
            else:
                aggs_test[id_]['cur_counter'].update(counter)

    chunk_num += 1
    print(f"Тестовый чанк {chunk_num}: уникальных id = {len(aggs_test)}")
    del df, simple_agg, paym_sum, cat_agg, last_rows, first_rows
    gc.collect()

print(f"Агрегация теста завершена. Уникальных клиентов: {len(aggs_test)}")

# ---- Формирование итогового DataFrame тестовых признаков ----
test_rows = []
for id_, d in aggs_test.items():
    cnt = d['cnt']
    if cnt == 0:
        continue
    row = {'id': id_}
    row['cnt_loans'] = cnt
    row['mean_credit_limit'] = d['sum_credit_limit'] / cnt
    row['mean_outstanding'] = d['sum_outstanding'] / cnt
    row['mean_util'] = d['sum_util'] / cnt
    row['mean_overdue'] = d['sum_overdue'] / cnt
    row['mean_max_overdue'] = d['sum_max_overdue'] / cnt
    row['mean_next_pay_summ'] = d['sum_next_pay_summ'] / cnt
    row['mean_pterm'] = d['sum_pterm'] / cnt
    row['mean_fterm'] = d['sum_fterm'] / cnt

    row['total_loans5'] = d['sum_loans5']
    row['total_loans530'] = d['sum_loans530']
    row['total_loans3060'] = d['sum_loans3060']
    row['total_loans6090'] = d['sum_loans6090']
    row['total_loans90'] = d['sum_loans90']
    row['weighted_overdue'] = (1*d['sum_loans5'] + 2*d['sum_loans530'] +
                               3*d['sum_loans3060'] + 4*d['sum_loans6090'] +
                               5*d['sum_loans90'])
    if d['sum_loans90'] > 0:
        row['max_overdue_level'] = 5
    elif d['sum_loans6090'] > 0:
        row['max_overdue_level'] = 4
    elif d['sum_loans3060'] > 0:
        row['max_overdue_level'] = 3
    elif d['sum_loans530'] > 0:
        row['max_overdue_level'] = 2
    elif d['sum_loans5'] > 0:
        row['max_overdue_level'] = 1
    else:
        row['max_overdue_level'] = 0

    row['outstanding_to_limit'] = d['sum_outstanding'] / (d['sum_credit_limit'] + 1e-9)
    row['overdue_to_limit'] = d['sum_overdue'] / (d['sum_credit_limit'] + 1e-9)
    row['next_paym_to_outstanding'] = d['sum_next_pay_summ'] / (d['sum_outstanding'] + 1e-9)

    row['last_util'] = d['last_util'] if d['last_util'] is not None else 0
    row['last_over2limit'] = d['last_over2limit'] if d['last_over2limit'] is not None else 0
    row['last_loans90'] = d['last_loans90'] if d['last_loans90'] is not None else 0
    row['last_credit_limit'] = d['last_credit_limit'] if d['last_credit_limit'] is not None else 0
    row['last_outstanding'] = d['last_outstanding'] if d['last_outstanding'] is not None else 0

    row['first_util'] = d['first_util'] if d['first_util'] is not None else 0
    row['first_credit_limit'] = d['first_credit_limit'] if d['first_credit_limit'] is not None else 0

    row['trend_util'] = row['last_util'] - row['first_util']
    row['trend_credit_limit'] = row['last_credit_limit'] - row['first_credit_limit']

    row['any_pclose_flag'] = int(d['any_pclose_flag'])
    row['any_fclose_flag'] = int(d['any_fclose_flag'])

    d['cnt_paym'] = cnt
    paym_mean = [s / d['cnt_paym'] for s in d['sum_paym']]
    row['avg_paym'] = np.mean(paym_mean)
    row['max_paym'] = np.max(paym_mean)
    row['std_paym'] = np.std(paym_mean)
    if len(paym_mean) >= 24:
        row['trend_paym_first12'] = np.mean(paym_mean[:12])
        row['trend_paym_last12'] = np.mean(paym_mean[-12:])
        row['trend_paym_diff'] = row['trend_paym_last12'] - row['trend_paym_first12']
    else:
        row['trend_paym_first12'] = np.nan
        row['trend_paym_last12'] = np.nan
        row['trend_paym_diff'] = np.nan

    if d['holder_counter']:
        row['mode_holder_type'] = d['holder_counter'].most_common(1)[0][0]
        row['nunique_holder_type'] = len(d['holder_counter'])
    else:
        row['mode_holder_type'] = -1
        row['nunique_holder_type'] = 0
    if d['status_counter']:
        row['mode_credit_status'] = d['status_counter'].most_common(1)[0][0]
        row['nunique_credit_status'] = len(d['status_counter'])
    else:
        row['mode_credit_status'] = -1
        row['nunique_credit_status'] = 0
    if d['type_counter']:
        row['mode_credit_type'] = d['type_counter'].most_common(1)[0][0]
        row['nunique_credit_type'] = len(d['type_counter'])
    else:
        row['mode_credit_type'] = -1
        row['nunique_credit_type'] = 0
    if d['cur_counter']:
        row['mode_account_cur'] = d['cur_counter'].most_common(1)[0][0]
        row['nunique_account_cur'] = len(d['cur_counter'])
    else:
        row['mode_account_cur'] = -1
        row['nunique_account_cur'] = 0

    test_rows.append(row)

df_test_features = pd.DataFrame(test_rows)
print(f"Размерность тестовых фичей: {df_test_features.shape}")

# ============================================================
# Применение тех же финансовых преобразований к тесту
# ============================================================
df_test = df_test_features.copy()

# (Вставляем все те же операции из блока "0. Добавление новых финансовых признаков")
# Для удобства скопируем весь блок, заменив df на df_test

df_test['free_limit_ratio'] = (df_test['mean_credit_limit'] - df_test['mean_outstanding']) / (df_test['mean_credit_limit'] + 1e-9)
df_test['overdue_to_credit_limit_ratio'] = df_test['mean_overdue'] / (df_test['mean_credit_limit'] + 1e-9)
df_test['payment_to_outstanding_ratio'] = df_test['mean_next_pay_summ'] / (df_test['mean_outstanding'] + 1e-9)
df_test['avg_overdue_per_loan'] = df_test['mean_overdue'] / (df_test['cnt_loans'] + 1e-9)
df_test['avg_max_overdue_per_loan'] = df_test['mean_max_overdue'] / (df_test['cnt_loans'] + 1e-9)
df_test['util_mean_to_max'] = df_test['mean_util'] / (df_test['last_util'] + 1e-9)
df_test['util_trend_ratio'] = (df_test['last_util'] + 1e-9) / (df_test['first_util'] + 1e-9)
df_test['has_overdue'] = (df_test['max_overdue_level'] > 0).astype(int)
df_test['high_overdue_ratio'] = ((df_test['total_loans3060'] + df_test['total_loans6090'] + df_test['total_loans90']) / (df_test['cnt_loans'] + 1e-9)).clip(0, 1)
df_test['paym_stability'] = 1.0 / (df_test['std_paym'] + 1e-9)
df_test['mean_term_ratio'] = df_test['mean_pterm'] / (df_test['mean_fterm'] + 1e-9)

df_test['payment_to_limit_ratio'] = df_test['mean_next_pay_summ'] / (df_test['mean_credit_limit'] + 1e-9)
df_test['max_overdue_to_outstanding_ratio'] = df_test['mean_max_overdue'] / (df_test['mean_outstanding'] + 1e-9)
df_test['overdue_intensity'] = (df_test['weighted_overdue'] + 1e-9) / (df_test['cnt_loans'] + 1e-9)
df_test['actual_to_plan_term_ratio'] = df_test['mean_fterm'] / (df_test['mean_pterm'] + 1e-9)
df_test['critical_util_ratio'] = ((df_test['mean_util'] > 0.95) & (df_test['mean_util'] <= 1.05)).astype(int)
df_test['last_vs_mean_util'] = df_test['last_util'] / (df_test['mean_util'] + 1e-9)
df_test['payment_discipline'] = 1.0 / (df_test['weighted_overdue'] + df_test['total_loans90'] + 1e-9)
df_test['risk_factor'] = (df_test['high_overdue_ratio'] * (1 - df_test['free_limit_ratio'].clip(0, 1)))
df_test['util_change_rate'] = (df_test['last_util'] - df_test['first_util']) / (df_test['first_util'] + 1e-9)
df_test['has_renegotiated'] = ((df_test['mean_fterm'] - df_test['mean_pterm']) > 0).astype(int)
df_test['financial_health_index'] = (
    df_test['free_limit_ratio'] * 0.3
    - df_test['overdue_to_credit_limit_ratio'] * 0.4
    - df_test['high_overdue_ratio'] * 0.3
)

df_test = df_test.fillna(0)

asa
Начинаем агрегацию тестовых данных...
Тестовый чанк 1: уникальных id = 214527
Тестовый чанк 2: уникальных id = 440682
Тестовый чанк 3: уникальных id = 674901
Тестовый чанк 4: уникальных id = 900000
Агрегация теста завершена. Уникальных клиентов: 900000
Размерность тестовых фичей: (900000, 45)

In [ ]:
data = pd.read_parquet('/kaggle/input/datasets/leonardcaceres/df-train-agg-alpha/df_train_agg.parquet')
print(data.shape)
data.head()

(2100000, 45)

,id,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,...,trend_paym_last12,trend_paym_diff,mode_holder_type,nunique_holder_type,mode_credit_status,nunique_credit_status,mode_credit_type,nunique_credit_type,mode_account_cur,nunique_account_cur
0,2250000,8,9.375,3.125000,15.375000,0.0,2.0,2.500000,10.375000,8.250000,...,3.041667,1.510417,1,1,3,2,4,3,1,1
1,2250001,2,9.500,2.500000,11.000000,0.0,2.0,1.500000,10.000000,8.000000,...,3.166667,0.333333,1,1,3,2,5,2,1,1
2,2250002,9,10.000,3.666667,11.333333,0.0,2.0,2.444444,10.333333,8.888889,...,1.453704,0.851852,1,2,2,2,3,4,1,1
3,2250003,4,5.750,3.000000,11.500000,0.0,2.0,2.000000,3.500000,6.250000,...,3.166667,0.958333,1,1,2,2,3,2,1,1
4,2250004,1,16.000,3.000000,16.000000,0.0,3.0,1.000000,2.000000,14.000000,...,0.416667,-0.250000,1,1,3,1,4,1,1,1

In [ ]:
df

,id,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,...,max_overdue_to_outstanding_ratio,overdue_intensity,actual_to_plan_term_ratio,critical_util_ratio,last_vs_mean_util,payment_discipline,risk_factor,util_change_rate,has_renegotiated,financial_health_index
0,2250000,8,9.375000,3.125000,15.375000,0.0,2.0,2.500000,10.375000,8.250000,...,0.640000,109.000000,0.795181,0,1.040650,0.001068,0.333333,0.0000,0,-0.100000
1,2250001,2,9.500000,2.500000,11.000000,0.0,2.0,1.500000,10.000000,8.000000,...,0.800000,109.000000,0.800000,0,0.545455,0.004274,0.263158,-0.6250,0,-0.078947
2,2250002,9,10.000000,3.666667,11.333333,0.0,2.0,2.444444,10.333333,8.888889,...,0.545455,108.333333,0.860215,0,0.794118,0.000955,0.366667,-0.4375,0,-0.110000
3,2250003,4,5.750000,3.000000,11.500000,0.0,2.0,2.000000,3.500000,6.250000,...,0.666667,109.000000,1.785714,0,0.173913,0.002137,0.521739,-0.8750,1,-0.156522
4,2250004,1,16.000000,3.000000,16.000000,0.0,3.0,1.000000,2.000000,14.000000,...,1.000000,103.000000,7.000000,0,1.000000,0.009009,0.187500,0.0000,1,-0.056250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2099995,1249995,13,10.384615,3.000000,14.923077,0.0,2.0,2.538462,9.307692,9.153846,...,0.666667,109.000000,0.983471,0,1.072165,0.000657,0.288889,0.0000,0,-0.086667
2099996,1249996,17,9.705882,2.470588,12.882353,0.0,2.0,2.235294,4.529412,4.705882,...,0.809524,109.000000,1.038961,0,0.232877,0.000503,0.254545,-0.8125,1,-0.076364
2099997,1249997,1,8.000000,4.000000,2.000000,0.0,2.0,3.000000,4.000000,8.000000,...,0.500000,109.000000,2.000000,0,1.000000,0.008547,0.500000,0.0000,1,-0.150000
2099998,1249998,5,7.400000,3.000000,16.000000,0.0,2.2,2.400000,9.000000,11.200000,...,0.733333,109.000000,1.244444,0,1.000000,0.001709,0.405405,0.0000,1,-0.121622
2099999,1249999,15,9.466667,3.200000,14.866667,0.0,2.0,2.000000,8.466667,9.866667,...,0.625000,109.000000,1.165354,0,0.739910,0.000570,0.338028,-0.3125,1,-0.101408

In [ ]:
df.columns

Index(['id', 'cnt_loans', 'mean_credit_limit', 'mean_outstanding', 'mean_util',
       'mean_overdue', 'mean_max_overdue', 'mean_next_pay_summ', 'mean_pterm',
       'mean_fterm', 'total_loans5', 'total_loans530', 'total_loans3060',
       'total_loans6090', 'total_loans90', 'weighted_overdue',
       'max_overdue_level', 'outstanding_to_limit', 'overdue_to_limit',
       'next_paym_to_outstanding', 'last_util', 'last_over2limit',
       'last_loans90', 'last_credit_limit', 'last_outstanding', 'first_util',
       'first_credit_limit', 'trend_util', 'trend_credit_limit',
       'any_pclose_flag', 'any_fclose_flag', 'avg_paym', 'max_paym',
       'std_paym', 'trend_paym_first12', 'trend_paym_last12',
       'trend_paym_diff', 'mode_holder_type', 'nunique_holder_type',
       'mode_credit_status', 'nunique_credit_status', 'mode_credit_type',
       'nunique_credit_type', 'mode_account_cur', 'nunique_account_cur',
       'flag', 'free_limit_ratio', 'overdue_to_credit_limit_ratio',
       'payment_to_outstanding_ratio', 'avg_overdue_per_loan',
       'avg_max_overdue_per_loan', 'util_mean_to_max', 'util_trend_ratio',
       'has_overdue', 'high_overdue_ratio', 'paym_stability',
       'mean_term_ratio', 'payment_to_limit_ratio',
       'max_overdue_to_outstanding_ratio', 'overdue_intensity',
       'actual_to_plan_term_ratio', 'critical_util_ratio', 'last_vs_mean_util',
       'payment_discipline', 'risk_factor', 'util_change_rate',
       'has_renegotiated', 'financial_health_index'],
      dtype='object')

In [ ]:
df_test

,id,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,...,max_overdue_to_outstanding_ratio,overdue_intensity,actual_to_plan_term_ratio,critical_util_ratio,last_vs_mean_util,payment_discipline,risk_factor,util_change_rate,has_renegotiated,financial_health_index
0,2000005,1,16.000000,2.000000,15.000000,0.0,2.000000,4.000000,4.000000,8.000000,...,1.000000,109.000000,2.000000,0,1.000000,0.008547,0.125000,0.0000,1,-0.037500
1,2000006,3,1.333333,2.666667,10.666667,0.0,2.000000,3.000000,4.000000,8.000000,...,0.750000,109.000000,2.000000,0,0.375000,0.002849,1.000000,-0.7500,1,-0.600000
2,2000011,18,7.277778,3.000000,15.611111,0.0,1.888889,2.500000,9.500000,7.666667,...,0.629630,109.000000,0.807018,0,1.024911,0.000475,0.412214,0.0000,0,-0.123664
3,2000018,14,9.214286,2.714286,15.000000,0.0,2.000000,2.285714,10.428571,6.928571,...,0.736842,106.285714,0.664384,0,1.066667,0.000625,0.294574,0.0000,0,-0.088372
4,2000021,8,9.250000,2.500000,13.750000,0.0,2.125000,1.375000,6.375000,8.625000,...,0.850000,109.000000,1.352941,0,0.000000,0.001068,0.270270,-1.0000,1,-0.081081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1499992,7,11.571429,3.000000,13.285714,0.0,2.000000,2.428571,9.857143,8.571429,...,0.666667,108.142857,0.869565,0,1.354839,0.001230,0.259259,0.1250,0,-0.077778
899996,1499994,4,11.750000,4.000000,15.750000,0.0,1.750000,2.750000,11.000000,9.750000,...,0.437500,109.000000,0.886364,0,1.206349,0.002137,0.340426,0.1875,0,-0.102128
899997,1499995,4,8.750000,3.250000,15.750000,0.0,2.000000,3.000000,11.750000,9.750000,...,0.615385,109.000000,0.829787,0,0.952381,0.002137,0.371429,-0.0625,0,-0.111429
899998,1499996,10,12.300000,3.100000,14.000000,0.0,2.000000,2.100000,10.100000,6.100000,...,0.645161,108.400000,0.603960,0,0.071429,0.000859,0.252033,-0.9375,0,-0.075610
899999,1499997,1,17.000000,2.000000,15.000000,0.0,2.000000,1.000000,17.000000,14.000000,...,1.000000,109.000000,0.823529,0,1.000000,0.008547,0.117647,0.0000,0,-0.035294

In [ ]:
# ============================================================
# Подготовка тестовых данных к предсказанию
# ============================================================
# Убеждаемся, что колонки совпадают с тренировочными (X_train)
# Если какой-то колонки нет в тесте, добавляем с нулями; если есть лишние — удаляем
# Приводим к порядку колонок X_train (сохраняя их набор)
missing_cols = set(df.drop(columns = 'flag').columns) - set(df_test.columns)
for col in missing_cols:
    X_test[col] = 0
# X_test = X_test[X_train.columns]   # одинаковый порядок и набор

missing_cols

set()

In [ ]:
df_test.to_parquet('df_test_agg.parquet')

In [ ]:
import joblib

final_model = joblib.load('/kaggle/working/lightgbm_final_model.pkl')
print("Модель загружена")

In [ ]:
df_test

,id,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,...,max_overdue_to_outstanding_ratio,overdue_intensity,actual_to_plan_term_ratio,critical_util_ratio,last_vs_mean_util,payment_discipline,risk_factor,util_change_rate,has_renegotiated,financial_health_index
0,2000005,1,16.000000,2.000000,15.000000,0.0,2.000000,4.000000,4.000000,8.000000,...,1.000000,109.000000,2.000000,0,1.000000,0.008547,0.125000,0.0000,1,-0.037500
1,2000006,3,1.333333,2.666667,10.666667,0.0,2.000000,3.000000,4.000000,8.000000,...,0.750000,109.000000,2.000000,0,0.375000,0.002849,1.000000,-0.7500,1,-0.600000
2,2000011,18,7.277778,3.000000,15.611111,0.0,1.888889,2.500000,9.500000,7.666667,...,0.629630,109.000000,0.807018,0,1.024911,0.000475,0.412214,0.0000,0,-0.123664
3,2000018,14,9.214286,2.714286,15.000000,0.0,2.000000,2.285714,10.428571,6.928571,...,0.736842,106.285714,0.664384,0,1.066667,0.000625,0.294574,0.0000,0,-0.088372
4,2000021,8,9.250000,2.500000,13.750000,0.0,2.125000,1.375000,6.375000,8.625000,...,0.850000,109.000000,1.352941,0,0.000000,0.001068,0.270270,-1.0000,1,-0.081081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1499992,7,11.571429,3.000000,13.285714,0.0,2.000000,2.428571,9.857143,8.571429,...,0.666667,108.142857,0.869565,0,1.354839,0.001230,0.259259,0.1250,0,-0.077778
899996,1499994,4,11.750000,4.000000,15.750000,0.0,1.750000,2.750000,11.000000,9.750000,...,0.437500,109.000000,0.886364,0,1.206349,0.002137,0.340426,0.1875,0,-0.102128
899997,1499995,4,8.750000,3.250000,15.750000,0.0,2.000000,3.000000,11.750000,9.750000,...,0.615385,109.000000,0.829787,0,0.952381,0.002137,0.371429,-0.0625,0,-0.111429
899998,1499996,10,12.300000,3.100000,14.000000,0.0,2.000000,2.100000,10.100000,6.100000,...,0.645161,108.400000,0.603960,0,0.071429,0.000859,0.252033,-0.9375,0,-0.075610
899999,1499997,1,17.000000,2.000000,15.000000,0.0,2.000000,1.000000,17.000000,14.000000,...,1.000000,109.000000,0.823529,0,1.000000,0.008547,0.117647,0.0000,0,-0.035294

In [ ]:
X_train

,cnt_loans,mean_credit_limit,mean_outstanding,mean_util,mean_overdue,mean_max_overdue,mean_next_pay_summ,mean_pterm,mean_fterm,total_loans5,...,max_overdue_to_outstanding_ratio,overdue_intensity,actual_to_plan_term_ratio,critical_util_ratio,last_vs_mean_util,payment_discipline,risk_factor,util_change_rate,has_renegotiated,financial_health_index
1299004,4,15.000000,3.500000,12.000000,0.0,2.000000,5.500000,4.000000,8.000000,24,...,0.571429,109.0,2.000000,0,1.333333,0.002137,0.233333,7.000000,1,-0.070000
1198066,15,9.333333,2.933333,15.933333,0.0,2.066667,2.533333,7.666667,9.400000,90,...,0.704545,109.0,1.226087,0,1.004184,0.000570,0.314286,0.000000,1,-0.094286
1586892,5,12.800000,2.800000,15.200000,0.0,2.000000,1.800000,6.800000,8.000000,30,...,0.714286,109.0,1.176471,0,1.052632,0.001709,0.218750,0.333333,1,-0.065625
1421683,8,6.625000,3.125000,11.500000,0.0,2.125000,2.125000,6.000000,11.125000,48,...,0.680000,109.0,1.854167,0,0.521739,0.001068,0.471698,-0.333333,1,-0.141509
1624139,3,11.333333,2.666667,11.000000,0.0,2.000000,1.666667,5.666667,8.000000,18,...,0.750000,109.0,1.411765,0,0.090909,0.002849,0.235294,-0.937500,1,-0.070588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422767,9,11.888889,2.888889,14.777778,0.0,2.111111,2.333333,8.555556,6.555556,54,...,0.730769,109.0,0.766234,0,0.203008,0.000950,0.242991,-0.812500,0,-0.072897
1217671,3,14.333333,3.333333,5.666667,0.0,2.000000,1.000000,2.000000,8.666667,18,...,0.600000,109.0,4.333333,0,0.705882,0.002849,0.232558,0.333333,1,-0.069767
638156,1,17.000000,2.000000,1.000000,0.0,2.000000,2.000000,17.000000,8.000000,6,...,1.000000,109.0,0.470588,1,1.000000,0.008547,0.117647,0.000000,0,-0.035294
48970,16,9.375000,2.875000,15.250000,0.0,2.000000,2.187500,8.687500,9.687500,96,...,0.695652,109.0,1.115108,0,0.721311,0.000534,0.306667,-0.312500,1,-0.092000
131460,1,11.000000,5.000000,3.000000,0.0,2.000000,5.000000,16.000000,9.000000,6,...,0.400000,109.0,0.562500,0,1.000000,0.008547,0.454545,0.000000,0,-0.136364

In [ ]:
# ============================================================
# Предсказание и сохранение результата
# ============================================================
X_test = df_test.drop(columns = 'id')
test_pred = final_model.predict_proba(X_test)[:, 1]

In [ ]:
submission = pd.DataFrame({'id': df_test['id'], 'flag': test_pred})
# submission['id'] = submission['id'].astype(int)
# submission['flag'] = submission['flag'].astype(float)
submission.to_csv('submission_10_iter.csv', index=False)
print("Предсказания сохранены в submission_10_iter.csv")

Предсказания сохранены в submission_10_iter.csv

In [ ]:
submission

             id      flag
0       2000005  0.080145
1       2000006  0.002448
2       2000011  0.014914
3       2000018  0.019316
4       2000021  0.009385
...         ...       ...
899995  1499992  0.096777
899996  1499994  0.035552
899997  1499995  0.016357
899998  1499996  0.036456
899999  1499997  0.033832

[900000 rows x 2 columns]

In [ ]:
pd.read_csv('submission_10_iter.csv')

             id      flag
0       2000005  0.080145
1       2000006  0.002448
2       2000011  0.014914
3       2000018  0.019316
4       2000021  0.009385
...         ...       ...
899995  1499992  0.096777
899996  1499994  0.035552
899997  1499995  0.016357
899998  1499996  0.036456
899999  1499997  0.033832

[900000 rows x 2 columns]